dataset: "cas(me)^2"
cas(me)^2:
  dataset: "cas(me)^2"
  cropped_root_path: "/kaggle/working/data/casme_2/cropped_apex"
  optflow_root_path: "/kaggle/working/data/casme_2/optflow_apex"
  feature_root_path: "/kaggle/working/data/casme_2/feature_apex"
  feature_segment_root_path:  "/kaggle/working/data/casme_2/feature_segment_apex"
  anno_csv_path: "/kaggle/input/csv-info/cas(me)_new.csv"
  CROPPED_SIZE: 500
  SEGMENT_LENGTH: 256
  RECEPTIVE_FILED: 15 # should be odd
  face_det_model_path: "/kaggle/input/checkpoint/pytorch/default/1/retinaface_Resnet50_Final.pth"
  landmark_model_path: "/kaggle/input/checkpoint/pytorch/default/1/san_checkpoint_49.pth.tar"


